name: Test Turk Ephemeral
on: workflow_dispatch

jobs:
  test-linux:
    runs-on: turk-ephemeral-ubuntu-22.04
    steps:
      - name: System Info
        run: |
          echo "Hello from Turk ephemeral runner!"
          echo "---"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "OS: $(uname -a)"
          echo "---"
          cat /etc/os-release
          echo "---"
          echo "Container will be destroyed after this job"
